# Generated by Django 4.2.25 on 2025-10-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='ai_assisted',
            field=models.BooleanField(default=False, help_text='True if an AI move has been requested for this game'),
        ),
    ]
