# Generated by Django 4.2.25 on 2025-10-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gamestate_ai_assisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='agent_class',
            field=models.CharField(default='RandomAgent', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aimodel',
            name='base_params',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='tunable_params',
            field=models.JSONField(default=dict),
        ),
    ]
