# Generated by Django 4.2.25 on 2025-11-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_aimodel_agent_class_aimodel_base_params_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='base_params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
