# Generated by Django 4.2.25 on 2025-10-31 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_aimodel_agent_class_aimodel_base_params_and_more'),
        ('users', '0002_profile_created_at_profile_games_played_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_configs',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='equipped_ai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.aimodel'),
        ),
    ]
